### ISSUE TITLE
Seller Page: Misaligned Button 

### ISSUE THREAD

**Issue by angelamiranda11** [imelilabourne/Shopping-App#13]
**Current Design/Behavior:**  
![image](https://user-images.githubusercontent.com/14832233/96425297-74a99b00-122e-11eb-8683-1d2fbae13372.png)

**Tip:** you can check your website's responsiveness by resizing your browser or Press `F12` then click `Toggle Device Toolbar` button. 
![image](https://user-images.githubusercontent.com/14832233/96425755-f3063d00-122e-11eb-8e7c-6102c3e14da5.png)

**Comment by seaninigabriel15** [comment]
![image](https://user-images.githubusercontent.com/70614920/97127488-b4afd700-1774-11eb-9c04-ecc7473bd067.png)

**Comment by seaninigabriel15** [comment]
![image](https://user-images.githubusercontent.com/70614920/97128191-a9f64180-1776-11eb-910a-d9837c3de7c8.png)

**Comment by angelamiranda11** [comment]
RESOLVED
