### ISSUE TITLE
Update Product: Nameless Fields and Field Sizes

### ISSUE THREAD

**Issue by angelamiranda11** [imelilabourne/Shopping-App#14]
**Current Design/Behavior:** 
-There are no field names (or tooltip for the icons) to indicate what fields they are. 
- The Product Description field's height is too short. 
![image](https://user-images.githubusercontent.com/14832233/96425969-319bf780-122f-11eb-9703-8a42e2a0f86c.png)

Note:
- if you know what fields will have long values, or will use multi-line, add the height to the text area. Don't be afraid to use the white spaces. 
- Don't forget to put field names. In some cases, browsers don't support all icons and may only display empty boxes.

**Comment by seaninigabriel15** [comment]
![image](https://user-images.githubusercontent.com/70614920/97127319-40753380-1774-11eb-9043-8d7fde9b6ecc.png)

**Comment by angelamiranda11** [comment]
RESOLVED
