### ISSUE TITLE
/Transact page: Empty tables

### ISSUE THREAD

**Issue by angelamiranda11** [imelilabourne/Shopping-App#15]
**Current design/behavior:** Only headers were shown. (Since there is no products sold?)
![image](https://user-images.githubusercontent.com/14832233/96426528-ec2bfa00-122f-11eb-86b2-f9000f9f9ebb.png)

**Suggestions:** If there are no sales, you can do either of the following:
1. Retain the headers, and put a 2nd row (merged into 1 column) indicating "No Sales Record" or something similar.  
2. Remove the table, and replace with an icon or message that indicates "No Sales Record" or something similar.

**Comment by seaninigabriel15** [comment]
![image](https://user-images.githubusercontent.com/70614920/97246806-30735780-1839-11eb-97c1-0471db273fe3.png)

**Comment by seaninigabriel15** [comment]
![image](https://user-images.githubusercontent.com/70614920/97413917-4cacec80-193e-11eb-9c38-d4af34a8b617.png)

**Comment by angelamiranda11** [comment]
RESOLVED
