### ISSUE TITLE
Footer: Not always at the bottom

### ISSUE THREAD

**Issue by angelamiranda11** [imelilabourne/Shopping-App#16]
**Current behavior:** in `/transact` page, footer is not fixed at the bottom of the page. 
![image](https://user-images.githubusercontent.com/14832233/96427095-b5a2af00-1230-11eb-802c-20b0f9f5fa8d.png)

**Comment by seaninigabriel15** [comment]
![image](https://user-images.githubusercontent.com/70614920/97126861-0192ae00-1773-11eb-8a64-a15398937750.png)

**Comment by angelamiranda11** [comment]
As of 10/28/2020, the footer is still not fixed at the bottom. Please see my screenshot below:

![image](https://user-images.githubusercontent.com/14832233/97402863-47e03c80-192e-11eb-9062-73b42c3b7998.png)

**Comment by seaninigabriel15** [comment]
![image](https://user-images.githubusercontent.com/70614920/97409941-60a21f80-1939-11eb-81f9-5898e21136eb.png)

**Comment by seaninigabriel15** [comment]
![image](https://user-images.githubusercontent.com/70614920/97410153-a9f26f00-1939-11eb-8165-da5ca8244be1.png)
 Navigation tabs with tab name

**Comment by angelamiranda11** [comment]
RESOLVED
