### ISSUE TITLE
Shop Name different in Seller Page and Transact Page

### ISSUE THREAD

**Issue by angelamiranda11** [imelilabourne/Shopping-App#19]
Sellet page: 
![image](https://user-images.githubusercontent.com/14832233/97404737-83303a80-1931-11eb-9974-428b7aaf8a61.png)

Transact page:
![image](https://user-images.githubusercontent.com/14832233/97404762-8cb9a280-1931-11eb-8e72-cb79bb911bd2.png)

**Comment by seaninigabriel15** [comment]
![image](https://user-images.githubusercontent.com/70614920/97410445-0786bb80-193a-11eb-83f3-e4b08ccc0d32.png)

**Comment by angelamiranda11** [comment]
RESOLVED
